{% extends "../../../../public/themes/adminlte/layouts/base.phtml" %}

{% block scriptHeader %} {% endblock %}

{% block header %} {% endblock %}

{% block content %}   

    <header class="main-header">
        <a href="#" class="logo">
            <span class="logo-mini"><b>S</b>CE</span>
            <span class="logo-lg"><b>Source</b> Code</span>
        </a>
        <nav class="navbar navbar-static-top" role="navigation">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon icon-envelope-o"></i>
                            <span class="label label-success">4</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 4 messages</li>
                            <li>
                                <ul class="menu">
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="{{ url('/themes/adminlte/images/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>Support Team <small><i class="icon icon-clock-o"></i> 5 mins</small></h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="{{ url('/themes/adminlte/images/user3-128x128.jpg') }}" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>AdminLTE Design Team <small><i class="icon icon-clock-o"></i> 2 hours</small></h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="{{ url('/themes/adminlte/images/user4-128x128.jpg') }}" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>Developers <small><i class="icon icon-clock-o"></i> Today</small></h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="{{ url('/themes/adminlte/images/user3-128x128.jpg') }}" class="img-circle" alt="User Image">
                                            </div>
                                            <h4> Sales Department <small><i class="icon icon-clock-o"></i> Yesterday</small></h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="{{ url('/themes/adminlte/images/user4-128x128.jpg') }}" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>Reviewers<small><i class="icon icon-clock-o"></i> 2 days</small></h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="#">See All Messages</a></li>
                      </ul>
                    </li>
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon icon-bell-o"></i><span class="label label-warning">10</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 10 notifications</li>
                            <li>
                                <ul class="menu">
                                    <li>
                                        <a href="#"><i class="icon icon-users text-aqua"></i> 5 new members joined today</a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="icon icon-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems</a>
                                    </li>
                                    <li>
                                      <a href="#"><i class="icon icon-users text-red"></i> 5 new members joined </a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="icon icon-shopping-cart text-green"></i> 25 sales made</a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="icon icon-user text-red"></i> You changed your username</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="#">View all</a></li>
                        </ul>
                    </li>
                    <li class="dropdown tasks-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon icon-flag-o"></i><span class="label label-danger">9</span>
                        </a>  
                        <ul class="dropdown-menu">
                            <li class="header">You have 9 tasks</li>
                            <li>
                                <ul class="menu">
                                    <li>
                                        <a href="#">
                                            <h3>Design some buttons <small class="pull-right">20%</small></h3>
                                            <div class="progress xs">
                                                <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">20% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <h3>Create a nice theme <small class="pull-right">40%</small></h3>
                                            <div class="progress xs">
                                                <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">40% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <h3>Some task I need to do <small class="pull-right">60%</small></h3>
                                            <div class="progress xs">
                                                <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">60% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <h3>Make beautiful transitions <small class="pull-right">80%</small></h3>
                                            <div class="progress xs">
                                                <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">80% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="#">View all tasks</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ url('/themes/adminlte/images/user2-160x160.jpg') }}" class="user-image" alt="User Image"><span class="hidden-xs">Eakkabin Jaikeawma</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{{ url('/themes/adminlte/images/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                                <p>Eakkabin Jaikeawma<small>Member since Nov. <?php echo date('Y'); ?></small></p>
                            </li>
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <aside class="main-sidebar">
        <section class="sidebar">
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{{ url('/themes/adminlte/images/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>Eakkabin Jaikeawma</p>
                    <a href="#"><i class="icon icon-circle text-success"></i> Online</a>
                </div>
            </div>
            <form action="{{ url('/search') }}" method="GET" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button type="submit" id="search-btn" class="btn btn-flat"><i class="icon icon-search"></i></button>
                    </span>
                </div>
            </form>
            <ul class="sidebar-menu">
                <?php $this->cache->cacheHTML($this->adminlte->nav->getNav(), false, 7, 'nav-frontend', '/application/runtime/caches/nav/' ); ?>
            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <section class="content-header">
            <h1>Dashboard <small>Control panel</small></h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="icon icon-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>
        <section class="content">
            {{ content() }}
        </section>
    </div>

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version </b> <?php echo CBaseSystem::$version; ?>
        </div>
        <strong>Copyright &copy; <?php echo date('Y'); ?> <a href="http://studio.drivesoft.co">DriveSoft Studio</a>.</strong> All rights reserved.
    </footer>

{% endblock %}

{% block scriptMainFooter %} {% endblock %} 

{% block scriptFooter %}  {% endblock %} 