<div class="row">
    <div class="col-xs-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
                <li><a href="#timeline" data-toggle="tab">Timeline</a></li>
                <li><a href="#settings" data-toggle="tab">Settings</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane" id="activity">
                    <div class="post">
                        <div class="user-block">
                            <img class="img-circle img-bordered-sm" src="{{ base.createUrl('vendor/adminLTE-2.3.0/img/user1-128x128.jpg') }}" alt="user image">
                            <span class='username'>
                                <a href="#">Jonathan Burke Jr.</a>
                                <a href='#' class='pull-right btn-box-tool'><i class='fa fa-times'></i></a>
                            </span>
                            <span class='description'>Shared publicly - 7:30 PM today</span>
                        </div>
                        <p>Lorem ipsum represents a long-held tradition for designers</p>
                    </div>
                </div>
                <div class="tab-pane" id="timeline">
                    timeline
                </div>
                <div class="tab-pane" id="settings">
                    settings
                </div>
            </div>
            </div>
    </div>
</div>