<div class="box-body">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-1 control-label">Email</label>
        <div class="col-sm-11">
            <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword3" class="col-sm-1 control-label">Password</label>
        <div class="col-sm-11">
            <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
        </div>
    </div>
</div>