<div class="row">
    <div class="col-xs-12">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Create</h3>
            </div>
            <div class="box-body">
                
                {{ form("/manager/source/save", "method" : 'POST', "class" : 'form-horizontal form-group') }}
                        
                    {{ partial('/product/_form') }}
                    
                    <div class="box-footer">
                        <div class="form-group ">
                            <div class="col-sm-offset-1 col-sm-11">
                                {{ hidden_field('hidden', 'name' : security.getTokenKey(), 'value' : security.getToken()) }}
                                {{ submit_button("Create", "class" : "btn btn-success btn-fill") }}
                            </div>
                        </div>
                    </div>
                    
                {{ end_form() }}
                
            </div>
        </div>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Data Table</h3>
            </div>
            <div class="box-body">
                {{ partial('/product/_table') }}
            </div>
        </div>
    </div>
</div>