<div class="row">
    <div class="col-xs-12">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Search</h3>&nbsp;|&nbsp;<a class="btn btn-success" href="{{ url('/manager/source/create') }}">Create</a>
            </div>
            <div class="box-body">
            </div>
        </div>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Data Table</h3>
            </div>
            <div class="box-body">
                
            </div>
        </div>
    </div>
</div>
